-- Complete, self-contained Meta Ads Center schema.
-- Safe to run when earlier Meta Ads migrations were not applied.

create table if not exists public.meta_ad_accounts (
  id text primary key,
  name text not null,
  currency text,
  timezone_name text,
  account_status integer,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meta_campaigns (
  id text primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  name text not null,
  objective text,
  status text,
  effective_status text,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  synced_at timestamptz not null default now()
);

create table if not exists public.meta_adsets (
  id text primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  campaign_id text references public.meta_campaigns(id) on delete cascade,
  name text not null,
  status text,
  effective_status text,
  optimization_goal text,
  billing_event text,
  daily_budget numeric,
  lifetime_budget numeric,
  start_time timestamptz,
  end_time timestamptz,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  synced_at timestamptz not null default now()
);

create table if not exists public.meta_ads (
  id text primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  campaign_id text references public.meta_campaigns(id) on delete cascade,
  adset_id text references public.meta_adsets(id) on delete cascade,
  name text not null,
  status text,
  effective_status text,
  meta_created_time timestamptz,
  meta_updated_time timestamptz,
  synced_at timestamptz not null default now()
);

create table if not exists public.meta_daily_insights (
  id bigint generated by default as identity primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  insight_level text not null check (insight_level in ('campaign', 'adset', 'ad')),
  campaign_id text,
  campaign_name text,
  adset_id text,
  adset_name text,
  ad_id text,
  ad_name text,
  date_start date not null,
  date_stop date not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  ctr numeric not null default 0,
  cpc numeric not null default 0,
  cpm numeric not null default 0,
  spend numeric not null default 0,
  synced_at timestamptz not null default now(),
  constraint meta_daily_insights_identity_uidx unique nulls not distinct
    (ad_account_id, insight_level, date_start, date_stop, campaign_id, adset_id, ad_id)
);

create table if not exists public.meta_ai_reports (
  id bigint generated by default as identity primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  best_campaign jsonb,
  worst_campaign jsonb,
  budget_suggestions text[] not null default '{}',
  analysis_source text not null default 'rules_v1',
  metrics_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists meta_campaigns_account_idx on public.meta_campaigns(ad_account_id);
create index if not exists meta_adsets_account_idx on public.meta_adsets(ad_account_id);
create index if not exists meta_adsets_campaign_idx on public.meta_adsets(campaign_id);
create index if not exists meta_ads_account_idx on public.meta_ads(ad_account_id);
create index if not exists meta_ads_campaign_idx on public.meta_ads(campaign_id);
create index if not exists meta_ads_adset_idx on public.meta_ads(adset_id);
create index if not exists meta_daily_insights_date_idx on public.meta_daily_insights(date_start desc, insight_level);
create index if not exists meta_daily_insights_campaign_date_idx on public.meta_daily_insights(campaign_id, date_start desc);
create index if not exists meta_daily_insights_adset_date_idx on public.meta_daily_insights(adset_id, date_start desc);
create index if not exists meta_daily_insights_ad_date_idx on public.meta_daily_insights(ad_id, date_start desc);
create index if not exists meta_ai_reports_account_created_idx on public.meta_ai_reports(ad_account_id, created_at desc);

-- Preserve data from either earlier draft table name, when present.
do $$
begin
  if to_regclass('public.meta_insights_daily') is not null then
    insert into public.meta_daily_insights (
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    )
    select
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    from public.meta_insights_daily
    on conflict (ad_account_id, insight_level, date_start, date_stop, campaign_id, adset_id, ad_id)
    do update set
      impressions = excluded.impressions,
      clicks = excluded.clicks,
      ctr = excluded.ctr,
      cpc = excluded.cpc,
      cpm = excluded.cpm,
      spend = excluded.spend,
      synced_at = excluded.synced_at;
  elsif to_regclass('public.meta_ads_insights_daily') is not null then
    insert into public.meta_daily_insights (
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    )
    select
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    from public.meta_ads_insights_daily
    on conflict (ad_account_id, insight_level, date_start, date_stop, campaign_id, adset_id, ad_id)
    do update set
      impressions = excluded.impressions,
      clicks = excluded.clicks,
      ctr = excluded.ctr,
      cpc = excluded.cpc,
      cpm = excluded.cpm,
      spend = excluded.spend,
      synced_at = excluded.synced_at;
  end if;
end $$;

alter table public.meta_ad_accounts enable row level security;
alter table public.meta_campaigns enable row level security;
alter table public.meta_adsets enable row level security;
alter table public.meta_ads enable row level security;
alter table public.meta_daily_insights enable row level security;
alter table public.meta_ai_reports enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'meta_ad_accounts', 'meta_campaigns', 'meta_adsets',
    'meta_ads', 'meta_daily_insights', 'meta_ai_reports'
  ] loop
    execute format('drop policy if exists %I on public.%I', table_name || '_read', table_name);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      table_name || '_read', table_name
    );
  end loop;
end $$;

notify pgrst, 'reload schema';

