-- Meta Ads Center V2: AI drafts and read-only analysis records.
-- This migration does not grant any capability to create or edit live Meta ads.

create table if not exists public.meta_generated_ads (
  id bigint generated by default as identity primary key,
  ad_account_id text references public.meta_ad_accounts(id) on delete set null,
  product text not null,
  goal text not null,
  audience text not null,
  budget numeric not null default 0 check (budget >= 0),
  ad_angle text not null,
  primary_text text not null,
  headline text not null,
  description text not null,
  cta text not null,
  creative_direction text not null,
  status text not null default 'draft' check (status in ('draft', 'approved', 'rejected')),
  human_approved boolean not null default false,
  model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.meta_ai_reports add column if not exists report_type text not null default 'summary';
alter table public.meta_ai_reports add column if not exists campaign_id text;
alter table public.meta_ai_reports add column if not exists campaign_name text;
alter table public.meta_ai_reports add column if not exists recommended_action text;
alter table public.meta_ai_reports add column if not exists recommendation_reason text;
alter table public.meta_ai_reports add column if not exists next_7_days_plan text[] not null default '{}';
alter table public.meta_ai_reports add column if not exists recommended_ad_angles text[] not null default '{}';
alter table public.meta_ai_reports add column if not exists input_snapshot jsonb not null default '{}'::jsonb;
alter table public.meta_ai_reports add column if not exists human_approved boolean not null default false;
alter table public.meta_ai_reports add column if not exists model text;
alter table public.meta_ai_reports add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'meta_ai_reports_report_type_check'
  ) then
    alter table public.meta_ai_reports add constraint meta_ai_reports_report_type_check
      check (report_type in ('summary', 'campaign_optimizer'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'meta_ai_reports_recommended_action_check'
  ) then
    alter table public.meta_ai_reports add constraint meta_ai_reports_recommended_action_check
      check (recommended_action is null or recommended_action in (
        'keep', 'pause', 'test_new_creative', 'increase_budget', 'reduce_budget', 'review'
      ));
  end if;
end $$;

create index if not exists meta_generated_ads_created_idx
  on public.meta_generated_ads(created_at desc);
create index if not exists meta_generated_ads_account_status_idx
  on public.meta_generated_ads(ad_account_id, status, created_at desc);
create index if not exists meta_ai_reports_type_created_idx
  on public.meta_ai_reports(report_type, created_at desc);
create index if not exists meta_ai_reports_campaign_created_idx
  on public.meta_ai_reports(campaign_id, created_at desc)
  where campaign_id is not null;

alter table public.meta_generated_ads enable row level security;

drop policy if exists meta_generated_ads_read on public.meta_generated_ads;
create policy meta_generated_ads_read
  on public.meta_generated_ads for select to anon, authenticated using (true);

-- Writes are intentionally restricted to the service-role Edge Function.
notify pgrst, 'reload schema';
