-- Customer Wallet CRM V2
-- Apply after checking that customers.id and orders.id are bigint in production.

alter table public.customers
  add column if not exists wallet_balance numeric(12, 2) not null default 0;

alter table public.orders
  add column if not exists payment_method text;

create table if not exists public.customer_wallet_transactions (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('top_up', 'deduct', 'refund', 'adjustment')),
  amount numeric(12, 2) not null,
  balance_before numeric(12, 2) not null,
  balance_after numeric(12, 2) not null check (balance_after >= 0),
  payment_method text,
  linked_order_id bigint references public.orders(id) on delete set null,
  remark text,
  created_at timestamptz not null default now(),
  created_by text,
  constraint customer_wallet_transaction_amount_check check (
    (transaction_type = 'adjustment' and amount <> 0)
    or (transaction_type <> 'adjustment' and amount > 0)
  )
);

create index if not exists customer_wallet_transactions_customer_created_idx
  on public.customer_wallet_transactions (customer_id, created_at desc);

create unique index if not exists customer_wallet_transactions_order_deduct_uidx
  on public.customer_wallet_transactions (linked_order_id)
  where transaction_type = 'deduct' and linked_order_id is not null;

create or replace function public.record_customer_wallet_transaction(
  p_customer_id bigint,
  p_transaction_type text,
  p_amount numeric,
  p_payment_method text default null,
  p_linked_order_id bigint default null,
  p_remark text default null,
  p_created_by text default null
)
returns public.customer_wallet_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before numeric(12, 2);
  v_after numeric(12, 2);
  v_transaction public.customer_wallet_transactions;
begin
  if p_transaction_type not in ('top_up', 'deduct', 'refund', 'adjustment') then
    raise exception 'Invalid wallet transaction type' using errcode = '22023';
  end if;

  if p_amount is null or p_amount = 0 or (p_transaction_type <> 'adjustment' and p_amount < 0) then
    raise exception 'Wallet amount must be greater than zero' using errcode = '22023';
  end if;

  select wallet_balance
    into v_before
    from public.customers
    where id = p_customer_id
    for update;

  if not found then
    raise exception 'Customer not found' using errcode = 'P0002';
  end if;

  if p_transaction_type = 'deduct' and p_linked_order_id is not null then
    select * into v_transaction
      from public.customer_wallet_transactions
      where linked_order_id = p_linked_order_id
        and transaction_type = 'deduct';
    if found then
      if v_transaction.customer_id <> p_customer_id or v_transaction.amount <> p_amount then
        raise exception 'Linked order already has a different wallet deduction' using errcode = '23505';
      end if;
      return v_transaction;
    end if;
  end if;

  v_after := case
    when p_transaction_type in ('top_up', 'refund') then v_before + p_amount
    when p_transaction_type = 'deduct' then v_before - p_amount
    else v_before + p_amount
  end;

  if v_after < 0 then
    raise exception 'Insufficient wallet balance' using errcode = 'P0001';
  end if;

  update public.customers
    set wallet_balance = v_after,
        updated_at = now()
    where id = p_customer_id;

  insert into public.customer_wallet_transactions (
    customer_id, transaction_type, amount, balance_before, balance_after,
    payment_method, linked_order_id, remark, created_by
  ) values (
    p_customer_id, p_transaction_type, p_amount, v_before, v_after,
    nullif(trim(p_payment_method), ''), p_linked_order_id,
    nullif(trim(p_remark), ''), nullif(trim(p_created_by), '')
  )
  returning * into v_transaction;

  return v_transaction;
end;
$$;

create or replace function public.pay_order_with_customer_wallet(
  p_customer_id bigint,
  p_order_id bigint,
  p_amount numeric,
  p_remark text default null,
  p_created_by text default null
)
returns public.customer_wallet_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transaction public.customer_wallet_transactions;
begin
  if not exists (
    select 1 from public.orders
    where id = p_order_id and customer_id = p_customer_id
  ) then
    raise exception 'Order does not belong to selected customer' using errcode = '22023';
  end if;

  v_transaction := public.record_customer_wallet_transaction(
    p_customer_id,
    'deduct',
    p_amount,
    'Customer Wallet',
    p_order_id,
    p_remark,
    p_created_by
  );

  update public.orders
    set payment_status = 'Paid',
        payment_method = 'Customer Wallet',
        order_status = case when lower(coalesce(order_status, '')) in ('completed', 'cancelled') then order_status else 'Paid' end,
        workflow_status = case when lower(coalesce(workflow_status, '')) in ('completed', 'cancelled') then workflow_status else 'Paid' end
    where id = p_order_id;

  return v_transaction;
end;
$$;

revoke all on function public.record_customer_wallet_transaction(bigint, text, numeric, text, bigint, text, text) from public;
revoke all on function public.pay_order_with_customer_wallet(bigint, bigint, numeric, text, text) from public;
grant execute on function public.record_customer_wallet_transaction(bigint, text, numeric, text, bigint, text, text) to anon, authenticated;
grant execute on function public.pay_order_with_customer_wallet(bigint, bigint, numeric, text, text) to anon, authenticated;

-- Ask PostgREST to expose the new table and RPC immediately after migration.
notify pgrst, 'reload schema';
