-- Align Meta Ads Center V1 with the production table names requested for reporting.

create table if not exists public.meta_insights_daily (
  id bigint generated by default as identity primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  insight_level text not null check (insight_level in ('campaign', 'adset', 'ad')),
  campaign_id text,
  campaign_name text,
  adset_id text,
  adset_name text,
  ad_id text,
  ad_name text,
  date_start date not null,
  date_stop date not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  ctr numeric not null default 0,
  cpc numeric not null default 0,
  cpm numeric not null default 0,
  spend numeric not null default 0,
  synced_at timestamptz not null default now(),
  constraint meta_insights_daily_identity_uidx unique nulls not distinct
    (ad_account_id, insight_level, date_start, date_stop, campaign_id, adset_id, ad_id)
);

create index if not exists meta_insights_daily_date_idx
  on public.meta_insights_daily(date_start desc, insight_level);
create index if not exists meta_insights_daily_campaign_idx
  on public.meta_insights_daily(campaign_id, date_start desc);

create table if not exists public.meta_ai_reports (
  id bigint generated by default as identity primary key,
  ad_account_id text not null references public.meta_ad_accounts(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  best_campaign jsonb,
  worst_campaign jsonb,
  budget_suggestions text[] not null default '{}',
  analysis_source text not null default 'rules_v1',
  metrics_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists meta_ai_reports_account_created_idx
  on public.meta_ai_reports(ad_account_id, created_at desc);

-- Preserve insights already synchronized by the earlier V1 draft, when present.
do $$
begin
  if to_regclass('public.meta_ads_insights_daily') is not null then
    insert into public.meta_insights_daily (
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    )
    select
      ad_account_id, insight_level, campaign_id, campaign_name, adset_id, adset_name,
      ad_id, ad_name, date_start, date_stop, impressions, clicks, ctr, cpc, cpm, spend, synced_at
    from public.meta_ads_insights_daily
    on conflict (ad_account_id, insight_level, date_start, date_stop, campaign_id, adset_id, ad_id)
    do update set
      impressions = excluded.impressions,
      clicks = excluded.clicks,
      ctr = excluded.ctr,
      cpc = excluded.cpc,
      cpm = excluded.cpm,
      spend = excluded.spend,
      synced_at = excluded.synced_at;
  end if;
end $$;

alter table public.meta_insights_daily enable row level security;
alter table public.meta_ai_reports enable row level security;

drop policy if exists meta_insights_daily_read on public.meta_insights_daily;
create policy meta_insights_daily_read on public.meta_insights_daily
  for select to anon, authenticated using (true);

drop policy if exists meta_ai_reports_read on public.meta_ai_reports;
create policy meta_ai_reports_read on public.meta_ai_reports
  for select to anon, authenticated using (true);

notify pgrst, 'reload schema';

